# ── Stage 1: Install dependencies ──────────────────────────────────────────
FROM oven/bun:1 AS deps

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile


# ── Stage 2: Production image ───────────────────────────────────────────────
FROM oven/bun:1-slim AS runner

WORKDIR /app

# Copy deps from previous stage
COPY --from=deps /app/node_modules ./node_modules

# Copy source
COPY src ./src
COPY drizzle ./drizzle
COPY drizzle.config.js ./
COPY tsconfig.json ./
COPY package.json ./

# Copy public assets (consent.html, authenticate.html)
COPY public ./public

# Copy certs (generated by key-gen.sh before building)
COPY cert ./cert

# Copy env file — or better, pass via docker-compose / runtime env vars
COPY .env ./

EXPOSE 8080

# Run migrations then start the server
CMD ["sh", "-c", "bun db:migrate && bun src/index.ts"]